#!/usr/bin/env python3

import json
import os
import time
import datetime
import random

BASE = os.path.expanduser("~/FYP-Project")
DECISIONS_LOG = os.path.join(BASE, "code/ai_module/logs/ai_decisions.jsonl")
DECOY_DIR = os.path.join(BASE, "assets/ai_generated")
DECOY_ACTIONS = os.path.join(BASE, "code/executor/decoy_actions.jsonl")

os.makedirs(DECOY_DIR, exist_ok=True)
os.makedirs(os.path.dirname(DECOY_ACTIONS), exist_ok=True)
open(DECISIONS_LOG, "a").close()
open(DECOY_ACTIONS, "a").close()

def follow(path):
    with open(path, "r") as fh:
        fh.seek(0, os.SEEK_END)
        while True:
            line = fh.readline()
            if not line:
                time.sleep(0.5)
                continue
            yield line

def write_jsonl(path, record):
    with open(path, "a") as fh:
        fh.write(json.dumps(record) + "\n")

def perform_action(decision):
    formatted_ts = datetime.datetime.utcnow().strftime("%d/%m/%Y - %H:%M:%S")
    ts_compact = datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S")
    src_ip = decision.get("src_ip", "unknown").replace(":", "-").replace("/", "-")
    action = decision.get("selected_action", "create_decoy_file")

    gen_id = decision.get("meta", {}).get("gen_id", "")
    base_name = f"{action}_{src_ip}_{ts_compact}_{gen_id}.txt"
    fpath = os.path.join(DECOY_DIR, base_name)

    ai_text = decision.get("response") or decision.get("description", "")
    meta = decision.get("meta", {})

    header = [
        f"// Decoy generated by Executor",
        f"// Timestamp: {formatted_ts}",
        f"// Src IP: {src_ip}",
        f"// Action: {action}",
        f"// Confidence: {decision.get('confidence', 0)}",
        f"// Template: {meta.get('template_file', 'builtin')}",
        "",
    ]

    content = "\n".join(header) + "\n" + ai_text + "\n"

    with open(fpath, "w") as fh:
        fh.write(content)

    engage_duration = round(random.uniform(0.5, 5.0), 2)
    size = os.path.getsize(fpath)

    rec = {
        "timestamp": formatted_ts,
        "src_ip": src_ip,
        "action": action,
        "file": fpath,
        "file_size": size,
        "gen_id": gen_id,
        "template": meta.get("template_file", "builtin"),
        "engage_duration_min": engage_duration
    }

    write_jsonl(DECOY_ACTIONS, rec)
    print(f"[Executor] Created decoy: {fpath} ({size} bytes, Engage: {engage_duration} min)")
    return rec

if __name__ == "__main__":
    print("[Executor] Watching for AI decisions...")
    for raw in follow(DECISIONS_LOG):
        try:
            dec = json.loads(raw)
        except Exception:
            continue

        if not dec.get("selected_action"):
            continue

        perform_action(dec)
